### ISSUE TITLE
git-lfs filter-process failed

### ISSUE THREAD

**Issue by wolf943134497** [eric-yyjau/pytorch-deepFEPE#1]
Hi @eric-yyjau  Thanks for excellent work!

can you put checkpoints and results on googledrive?  git clone encountered an error: external filter 'git-lfs filter-process' failed

**Comment by eric-yyjau** [comment]
Hi @wolf943134497,

Thank you for your interest. Sure. The results can be downloaded through the link (https://drive.google.com/drive/folders/18WHK8V7orm7-Pqd4KouPSM-da2CD8xN4?usp=sharing)
as described in the section `our-pretrained-models` (https://github.com/eric-yyjau/pytorch-deepFEPE#our-pretrained-models).

**Comment by wolf943134497** [comment]
Thanks for your quick reply! It works. Thanks for excellent work again!
